security:
    encoders:
        App\Entity\User: bcrypt # or argon2i

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
            entity: { class: App:User , property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api/token
            anonymous: true
#            remember_me:
#                samesite: 'strict'

        api:
            pattern:  ^/api
            anonymous: true
            http_basic: ~
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
    access_control:
        - { path: ^/api/get-top-players, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/get-top-teams, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/forgotPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/puzzles, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/contests, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/contests/get/^, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/^, role: ROLE_USER }
        - { path: ^/api/my_puzzles, role: ROLE_USER }
        - { path: ^/api/puzzles/create, role: ROLE_USER }
        - { path: ^/api/puzzles/^, role: ROLE_USER }
        - { path: ^/api/puzzles/destroy/^, role: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
          # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
